version: '2'
volumes:
  pulseaudio_shared_cookie:
services:
  pulseaudio-client2:
    build: ./pulseaudio-client2
    network_mode: host
    #privileged: true
    #labels:
     # io.balena.features.dbus: '1'
     # io.balena.features.kernel-modules: '1'
    #environment:
     # - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
  pulseaudio-client1:
    build: ./pulseaudio-client1
    network_mode: host
    labels:
      io.balena.features.dbus: '1'
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
  pulseaudio-server:
    # based on https://github.com/woahbase/alpine-pulseaudio
    build: ./pulseaudio-server
    #restart: always
    network_mode: host
    #privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
    devices:
      - "/dev/snd:/dev/snd/"
      - "/dev/bus/usb:/dev/bus/usb"
    cap_add:
      - NET_ADMIN
    ports:
      - "4713:4713"
    volumes:
      - 'pulseaudio_shared_cookie:/tmp/shared_cookie'
    environment:
      - DISABLEBLUETOOTH=true
      - UDEV=1
      - PGID=1000
      - PUID=1000
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket