version: '2'
volumes:
  pulseaudio_shared_cookie:
services:
  pa-server:
    build: ./pa-server
    #privileged: true
    #labels:
     # io.balena.features.dbus: '1'
     # io.balena.features.kernel-modules: '1'
    #environment:
     # - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
  pa-client1:
    build: ./pa-client1
  alpine-pa:
    # based on https://github.com/woahbase/alpine-pulseaudio
    build: ./alpine-pa
    #restart: always
    network_mode: host
    #privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
    devices:
      - "/dev/snd:/dev/snd/"
      - "/dev/usb/snd:/dev/usb/snd"
    cap_add:
      - NET_ADMIN
    ports:
      - "4713:4713"
    volumes:
      - 'pulseaudio_shared_cookie:/tmp/shared_cookie'
    environment:
      - UDEV=1
      - PGID=1000
      - PUID=1000
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket